### ISSUE TITLE
malloc.h not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chyh1990/gil-contributions#7]
```
What steps will reproduce the problem?
Compile with g++ 4.2 (apple) on a mac (10.6 in my case).

What is the expected output? What do you see instead?
gil_extensions/boost/gil/extension/io_new/detail/path_spec.hpp:23:20: error: 
malloc.h: No such file or directory


What version of the product are you using? On what operating system?
the latest svn trunk (r657)

Please provide any additional information below.
Removing the line allowed my code to compile.  What does malloc.h provide that 
cstdlib does not?  On the mac malloc.h is in malloc/malloc.h

```

Original issue reported on code.google.com by `ktarp...@gmail.com` on 11 May 2011 at 2:05

**Comment by GoogleCodeExporter** [comment]
```
I am using boost 1.45.0
```

Original comment by `ktarp...@gmail.com` on 11 May 2011 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
Fixed.
```

Original comment by `chhenn...@gmail.com` on 21 Apr 2012 at 8:53
- Changed state: **Fixed**
